### ISSUE TITLE
'PUBCHEM_COMPOUND' in the statistics for pathway XY is not a valid MainResource

### ISSUE THREAD

**Issue by jgriss** [reactome/gsa-backend#22] opened 2022-04-08 11:51 UTC
## Description

For a increasing number of analysis requests, uploading the Reactome Analysis object for the visualization fails with the error: 
```
'PUBCHEM_COMPOUND' in the statistics for pathway XY is not a valid MainResource
```

## Cause

This is the workflow:

  1. Map all user submitted identifiers using the mapping service (`AnalysisService/mapping/projection/?interactors=true`)
  2. Perform an over-representation analysis using the AnalysisService (`/AnalysisService/identifiers/projection`)

When users submit NCBI gene identifiers (only numeric values) the "statistics" for some pathways suddenly contain "CHEBI" as a resource.

This list of ids triggers the error:
[ids.zip](https://github.com/reactome/gsa-backend/files/8451524/ids.zip)

## Issue

It is unclear why a "resource" that is returned by the AnalysisService is subsequently not accepted for the pathway visualization.

**Comment by EliotRagueneau** [comment] 2023-10-16 10:03
Is it still happening? I struggle to reproduce it :/

**Comment by jgriss** [comment] 2023-10-18 05:51
I will check. Unfortunately, this seems to occur a bit randomly.

**Comment by jgriss** [comment] 2023-10-20 13:19
Hi @EliotRagueneau 

The error occurred again today:

```
 Failed upload result to REACTOME: {"code":400,"reason":"Bad Request","messages":["'PUBCHEM_COMPOUND' in the statistics for pathway 52 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 29 for pathway 52 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 349 for pathway 52 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 47 of pathway 52","'PUBCHEM_COMPOUND' in the statistics for pathway 62 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 507 for pathway 62 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 228 of pathway 62","'PUBCHEM_COMPOUND' in the statistics for pathway 64 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 511 for pathway 64 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 229 of pathway 64","'PUBCHEM_COMPOUND' in the statistics for pathway 108 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 126 for pathway 108 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 108","'PUBCHEM_COMPOUND' is not a valid resources for reaction 114 of pathway 108","'PUBCHEM_COMPOUND' in the statistics for pathway 131 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 808 for pathway 131 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 902 for pathway 131 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 295 of pathway 131","'PUBCHEM_COMPOUND' is not a valid resources for reaction 384 of pathway 131","'PUBCHEM_COMPOUND' in the statistics for pathway 218 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 98 for pathway 218 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 32 of pathway 218","'PUBCHEM_COMPOUND' in the statistics for pathway 438 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 859 for pathway 438 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 934 for pathway 438 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 29 of pathway 438","'PUBCHEM_COMPOUND' is not a valid resources for reaction 356 of pathway 438","'PUBCHEM_COMPOUND' is not a valid resources for reaction 884 of pathway 438","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1146 of pathway 438","'PUBCHEM_COMPOUND' in the statistics for pathway 439 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 251 for pathway 439 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 309 for pathway 439 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 439","'PUBCHEM_COMPOUND' is not a valid resources for reaction 14 of pathway 439","'PUBCHEM_COMPOUND' is not a valid resources for reaction 15 of pathway 439","'PUBCHEM_COMPOUND' is not a valid resources for reaction 104 of pathway 439","'PUBCHEM_COMPOUND' in the statistics for pathway 510 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 44 for pathway 510 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 112 for pathway 510 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 2 of pathway 510","'PUBCHEM_COMPOUND' is not a valid resources for reaction 21 of pathway 510","'PUBCHEM_COMPOUND' is not a valid resources for reaction 22 of pathway 510","'PUBCHEM_COMPOUND' in the statistics for pathway 610 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 29 for pathway 610 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 15 of pathway 610","'PUBCHEM_COMPOUND' in the statistics for pathway 682 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 66 for pathway 682 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 12 of pathway 682","'PUBCHEM_COMPOUND' in the statistics for pathway 721 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 71 for pathway 721 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 61 of pathway 721","'PUBCHEM_COMPOUND' in the statistics for pathway 764 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 669 for pathway 764 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 727 for pathway 764 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 16 of pathway 764","'PUBCHEM_COMPOUND' is not a valid resources for reaction 106 of pathway 764","'PUBCHEM_COMPOUND' is not a valid resources for reaction 249 of pathway 764","'PUBCHEM_COMPOUND' is not a valid resources for reaction 254 of pathway 764","'PUBCHEM_COMPOUND' in the statistics for pathway 802 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 52 for pathway 802 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 33 of pathway 802","'PUBCHEM_COMPOUND' in the statistics for pathway 854 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 14 for pathway 854 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 20 for pathway 854 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 12 of pathway 854","'PUBCHEM_COMPOUND' in the statistics for pathway 1343 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 5 for pathway 1343 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 1343","'PUBCHEM_COMPOUND' is not a valid resources for reaction 8 of pathway 1343","'PUBCHEM_COMPOUND' in the statistics for pathway 1521 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 3 for pathway 1521 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 7 of pathway 1521","'PUBCHEM_COMPOUND' in the statistics for pathway 1820 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 16 for pathway 1820 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 6 of pathway 1820","'PUBCHEM_COMPOUND' in the statistics for pathway 1821 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 16 for pathway 1821 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 7 of pathway 1821","'PUBCHEM_COMPOUND' in the statistics for pathway 1844 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 845 for pathway 1844 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 918 for pathway 1844 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 17 of pathway 1844","'PUBCHEM_COMPOUND' is not a valid resources for reaction 131 of pathway 1844","'PUBCHEM_COMPOUND' is not a valid resources for reaction 328 of pathway 1844","'PUBCHEM_COMPOUND' is not a valid resources for reaction 340 of pathway 1844","'PUBCHEM_COMPOUND' in the statistics for pathway 1878 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 33 for pathway 1878 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 1878","'PUBCHEM_COMPOUND' is not a valid resources for reaction 17 of pathway 1878","'PUBCHEM_COMPOUND' in the statistics for pathway 2322 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 2 for pathway 2322 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 5 for pathway 2322 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 2322","'PUBCHEM_COMPOUND' is not a valid resources for reaction 4 of pathway 2322","'PUBCHEM_COMPOUND' is not a valid resources for reaction 5 of pathway 2322","'PUBCHEM_COMPOUND' in the statistics for pathway 2370 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 2 for pathway 2370 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1 of pathway 2370","'PUBCHEM_COMPOUND' in the statistics for pathway 2429 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 19 for pathway 2429 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 2429","'PUBCHEM_COMPOUND' in the statistics for pathway 2540 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 428 for pathway 2540 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1173 of pathway 2540","'PUBCHEM_COMPOUND' in the statistics for pathway 2554 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 70 for pathway 2554 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 62 of pathway 2554","'PUBCHEM_COMPOUND' in the statistics for pathway 2575 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 124 for pathway 2575 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 105 of pathway 2575","'PUBCHEM_COMPOUND' is not a valid resources for reaction 108 of pathway 2575","'PUBCHEM_COMPOUND' is not a valid resources for reaction 116 of pathway 2575","'PUBCHEM_COMPOUND' in the statistics for pathway 2577 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 6 for pathway 2577 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 6 of pathway 2577","'PUBCHEM_COMPOUND' is not a valid resources for reaction 8 of pathway 2577","'PUBCHEM_COMPOUND' is not a valid resources for reaction 10 of pathway 2577"]}
```

The process is as follows:
  1. I use the ReactomeAnalysis service to get a "blueprint" for the result 
      ```AnalysisService/identifiers/projection?interactors={interactors}&pageSize=0&page=1&sortBy=ENTITIES_PVALUE&order=ASC&resource=TOTAL&pValue=1&includeDisease={disease}```
  2. The results of the pathway analysis are "injected" into the blueprint
  3. The updated blueprint data is sent back to Reactome

The PUBCHEM_COMPOUND resource is already returned by the Reactome Analysis service. So there's no way I could change this.

**Comment by jgriss** [comment] 2023-10-24 06:10
Hi @EliotRagueneau ,

Today, we had another case in the logs:

```
[2023-10-24 04:06:59,665] ERROR [1] [reactome_analysis_worker.reactome_analysis_worker._on_new_analysis:458] Failed to submit result to Reactome (a2655d03-7222-11ee-a82b-ee10d65dcb74): Failed upload result to REACTOME: {"code":400,"reason":"Bad Request","messages":["'PUBCHEM_COMPOUND' in the statistics for pathway 55 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1088 for pathway 55 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1091 for pathway 55 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1209 for pathway 55 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 312 of pathway 55","'PUBCHEM_COMPOUND' is not a valid resources for reaction 405 of pathway 55","'PUBCHEM_COMPOUND' in the statistics for pathway 75 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 243 for pathway 75 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 28 of pathway 75","'PUBCHEM_COMPOUND' in the statistics for pathway 81 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 122 for pathway 81 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 124 for pathway 81 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 32 of pathway 81","'PUBCHEM_COMPOUND' in the statistics for pathway 86 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 223 for pathway 86 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 410 for pathway 86 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 417 for pathway 86 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 47 of pathway 86","'PUBCHEM_COMPOUND' in the statistics for pathway 108 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 247 for pathway 108 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 108","'PUBCHEM_COMPOUND' is not a valid resources for reaction 131 of pathway 108","'PUBCHEM_COMPOUND' in the statistics for pathway 195 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 91 for pathway 195 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 93 for pathway 195 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 11 of pathway 195","'PUBCHEM_COMPOUND' in the statistics for pathway 354 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 608 for pathway 354 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 229 of pathway 354","'PUBCHEM_COMPOUND' in the statistics for pathway 392 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 4 for pathway 392 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 8 for pathway 392 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 6 of pathway 392","'PUBCHEM_COMPOUND' in the statistics for pathway 410 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 612 for pathway 410 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 230 of pathway 410","'PUBCHEM_COMPOUND' in the statistics for pathway 561 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 26 for pathway 561 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 72 for pathway 561 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 2 of pathway 561","'PUBCHEM_COMPOUND' is not a valid resources for reaction 15 of pathway 561","'PUBCHEM_COMPOUND' is not a valid resources for reaction 16 of pathway 561","'PUBCHEM_COMPOUND' in the statistics for pathway 607 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 39 for pathway 607 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 15 of pathway 607","'PUBCHEM_COMPOUND' in the statistics for pathway 744 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 36 for pathway 744 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 64 of pathway 744","'PUBCHEM_COMPOUND' in the statistics for pathway 779 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 300 for pathway 779 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 363 for pathway 779 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 779","'PUBCHEM_COMPOUND' is not a valid resources for reaction 17 of pathway 779","'PUBCHEM_COMPOUND' is not a valid resources for reaction 18 of pathway 779","'PUBCHEM_COMPOUND' is not a valid resources for reaction 134 of pathway 779","'PUBCHEM_COMPOUND' in the statistics for pathway 850 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 61 for pathway 850 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 33 of pathway 850","'PUBCHEM_COMPOUND' in the statistics for pathway 1093 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 14 for pathway 1093 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 4 of pathway 1093","'PUBCHEM_COMPOUND' is not a valid resources for reaction 10 of pathway 1093","'PUBCHEM_COMPOUND' in the statistics for pathway 1199 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 12 for pathway 1199 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 32 for pathway 1199 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 40 for pathway 1199 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 12 of pathway 1199","'PUBCHEM_COMPOUND' in the statistics for pathway 1292 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 54 for pathway 1292 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 5 of pathway 1292","'PUBCHEM_COMPOUND' in the statistics for pathway 1602 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1076 for pathway 1602 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1170 for pathway 1602 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 18 of pathway 1602","'PUBCHEM_COMPOUND' is not a valid resources for reaction 881 of pathway 1602","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1224 of pathway 1602","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1394 of pathway 1602","'PUBCHEM_COMPOUND' in the statistics for pathway 1902 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 24 for pathway 1902 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 7 of pathway 1902","'PUBCHEM_COMPOUND' in the statistics for pathway 1903 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 24 for pathway 1903 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 7 of pathway 1903","'PUBCHEM_COMPOUND' in the statistics for pathway 2030 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 17 for pathway 2030 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 2030","'PUBCHEM_COMPOUND' is not a valid resources for reaction 20 of pathway 2030","'PUBCHEM_COMPOUND' in the statistics for pathway 2078 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 801 for pathway 2078 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 864 for pathway 2078 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 16 of pathway 2078","'PUBCHEM_COMPOUND' is not a valid resources for reaction 120 of pathway 2078","'PUBCHEM_COMPOUND' is not a valid resources for reaction 280 of pathway 2078","'PUBCHEM_COMPOUND' is not a valid resources for reaction 288 of pathway 2078","'PUBCHEM_COMPOUND' in the statistics for pathway 2366 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 6 for pathway 2366 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 2366","'PUBCHEM_COMPOUND' is not a valid resources for reaction 4 of pathway 2366","'PUBCHEM_COMPOUND' is not a valid resources for reaction 5 of pathway 2366","'PUBCHEM_COMPOUND' in the statistics for pathway 2407 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 2 for pathway 2407 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 3 for pathway 2407 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1 of pathway 2407","'PUBCHEM_COMPOUND' in the statistics for pathway 2467 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 24 for pathway 2467 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 3 of pathway 2467","'PUBCHEM_COMPOUND' in the statistics for pathway 2486 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1024 for pathway 2486 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 1110 for pathway 2486 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 17 of pathway 2486","'PUBCHEM_COMPOUND' is not a valid resources for reaction 145 of pathway 2486","'PUBCHEM_COMPOUND' is not a valid resources for reaction 360 of pathway 2486","'PUBCHEM_COMPOUND' is not a valid resources for reaction 374 of pathway 2486","'PUBCHEM_COMPOUND' in the statistics for pathway 2579 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 107 for pathway 2579 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 69 of pathway 2579","'PUBCHEM_COMPOUND' in the statistics for pathway 2599 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 235 for pathway 2599 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 1242 of pathway 2599","'PUBCHEM_COMPOUND' in the statistics for pathway 2610 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 154 for pathway 2610 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 380 for pathway 2610 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 110 of pathway 2610","'PUBCHEM_COMPOUND' is not a valid resources for reaction 113 of pathway 2610","'PUBCHEM_COMPOUND' is not a valid resources for reaction 123 of pathway 2610","'PUBCHEM_COMPOUND' in the statistics for pathway 2612 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 49 for pathway 2612 is not a valid MainResource","'PUBCHEM_COMPOUND' for the mapping 1 of entity 124 for pathway 2612 is not a valid MainResource","'PUBCHEM_COMPOUND' is not a valid resources for reaction 5 of pathway 2612","'PUBCHEM_COMPOUND' is not a valid resources for reaction 7 of pathway 2612","'PUBCHEM_COMPOUND' is not a valid resources for reaction 13 of pathway 2612"]}
```

**Comment by EliotRagueneau** [comment] 2023-11-06 15:40
After a deeper look, it seems that's the normal URL for ChEBI webservices, so maybe sometimes we have slight SSL issues, but they do not seem too problematic for end users as they are uncorrelated to this specific issue, also I'm super dumb because I confused ChEBI and PUBCHEM.

Regarding PUBCHEM_COMPOUND specifically, it seems when we are checking the validity of external statistics imports, we are more stringent than what we export from the mapping
```java
    //DEFINES the main resources (and those to use as main resources in case the first ones are not found.
    public enum MAIN { UNIPROT, ENSEMBL, MIRBASE, CHEBI, IUPHAR, NCBI_NUCLEOTIDE }
    //NOTE: The idea is to get rid of the auxMainResources by being in touch with curators and find out whether a
    //main resource identifier can be used in the PhysicalEntities where no main resource was found
    public enum AUX { NCBI_PROTEIN, EMBL, COMPOUND, PUBCHEM_COMPOUND}
```

PubCHEM somehow has been classified as an auxiliary resource, and this is creating the problem as when we are reading external analysis, we are checking that resources are "valid", which basically just checks if they are among the main resources or if it is "TOTAL". 

I therefore see 2 solutions: either we accept PubChem as a main ressource, or we avoid sending PubChem data upfront in the workflow.

I personally would be more incline to make it a main resource but I will check with curators and Guanming if that's alright.

**Comment by jgriss** [comment] 2023-11-07 07:07
Hi @EliotRagueneau ,

Here is my "issue": I actually do not add / remove any resources to the data structure. I actually perform the analysis to get the data structure as a "blueprint" where I simply inject the results of the expression-level based gene set analysis.

For our analyses, users actually never upload any chemical compounds - but only gene / protein ids. So I don't really know why the PUBCHEM_COMPOUND is added at all.

To me, the cleanest solution would be if the blueprint / result object that I receive from the analysis system is already valid to be uploaded again

**Comment by EliotRagueneau** [comment] 2023-11-07 16:47
We have discussed this issue with the full reactome team, and we agreed to add a parameter to our analysis endpoints, specially the ones you are using, called "importable" to filter out all resources which are not valid for further down import. 

If I understand correctly your workflow, it concerns mostly `AnalysisService/mapping/projection` and  `/AnalysisService/identifiers/projection`, right?

**Comment by EliotRagueneau** [comment] 2023-11-14 15:30
Hi Johannes,

I've deployed to dev server a new analysis service including "importableOnly" parameters everywhere I needed (probably at a lot more places that you needed).

Could you please test it to check if it is working as you expect.
I suggest you to do ana analysis with the following gene identifiers : 
```
192169
104799
244187
```
**104799** is the important one since it is the one mapping both to [PubCHEM](https://pubchem.ncbi.nlm.nih.gov/compound/Fotemustine) and to [UniProt](https://www.uniprot.org/uniprotkb/Q15121/entry) thanks to a [MGI](https://www.informatics.jax.org/marker/MGI:104799) [Xref](https://reactome.org/content/schema/instance/browser/11936182).

**Comment by EliotRagueneau** [comment] 2024-03-26 14:41
Sicne we didn't receive any reply, the code changes never got integrated and we have moved on to other issues, so the new importableOnly filter is no longer available on dev server.

Once you are ready to test it, please ask us to redeploy the API.

For now, the changes are living on the `feature/analysis-importable` branch of our major repositories

**Comment by jgriss** [comment] 2024-04-04 13:33
@EliotRagueneau First tests worked. I just tested running the updated code with the current production system. Adding the parameter even though it's not yet there doesn't seem to be causing problems. So I'll deploy the change on my side during the next release

**Comment by EliotRagueneau** [comment] 2024-04-04 14:19
Awesome! I'll integrate this new feature officially then :D
Thanks for having tested it !

**Comment by jgriss** [comment] 2024-04-04 14:27
Hi @EliotRagueneau 

Another update: In a second more in-depth test, adding the parameter removed **all** identifiers from the dataset

What I was expecting is that only the PUBCHEM resource would be removed

**Comment by jgriss** [comment] 2024-04-04 14:28
I'll keep on investigating

**Comment by EliotRagueneau** [comment] 2024-04-04 14:34
You're rightit's not what i expected either, maybe something went wrong when merging changes, I'm checking it

**Comment by EliotRagueneau** [comment] 2024-04-04 16:14
Okay sorry about that, it came from an error from myself.
Basically, identifiers like `104799` are indeed Xref coming from Uniprot, but referencing MGI database, and I was performing the test on the xref origin database instead of the mapped entity database (so I was checking if MGI was a main resource for us, instead of Uniprot).

I've fixed that so now, we have outputs which do make more sense I think:
```json
[
  {
    "identifier": "192169",
    "mapsTo": []
  },
  {
    "identifier": "104799",
    "mapsTo": [
      {
        "resource": "UNIPROT",
        "identifier": "Q15121"
      }
    ]
  },
  {
    "identifier": "244187",
    "mapsTo": [
      {
        "resource": "UNIPROT",
        "identifier": "Q8NGH8"
      }
    ]
  }
]
``` 
is now the output when filtering for importables, and indeed, comparing with the results non filtered, we are indeed excluding non main entities:
```json
[
  {
    "identifier": "192169",
    "mapsTo": []
  },
  {
    "identifier": "104799",
    "mapsTo": [
      {
        "resource": "PUBCHEM_COMPOUND",
        "identifier": "104799"
      },
      {
        "resource": "UNIPROT",
        "identifier": "Q15121"
      }
    ]
  },
  {
    "identifier": "244187",
    "mapsTo": [
      {
        "resource": "UNIPROT",
        "identifier": "Q8NGH8"
      }
    ]
  }
]
```

I would therefore encourage you to test again to see if the problematic dataset is working as you expect now

**Comment by jgriss** [comment] 2024-04-04 16:45
Hi @EliotRagueneau ,

The dataset works again, but unfortunately, the PUBCHEM error also persists. I just rebuilt the application to ensure the new `importableOnly=true` parameter is set in all calls.

**Comment by EliotRagueneau** [comment] 2024-04-05 09:30
Could you please tell me all the endpoints you are using from Reactome? 
Maybe one of them doesn't support importableOnly yet

**Comment by EliotRagueneau** [comment] 2024-04-05 09:35
Actually I think I found them all in the repo, and I think the problem comes from https://github.com/reactome/gsa-backend/blob/5d3db77f4ce6d912ff126969fd9c3e609f463db0/reactome_analysis_worker/reactome_analysis_worker/result_converter.py#L93-L94 which for now doesn't support importableOnly. I'll add that immediately.

**Comment by jgriss** [comment] 2024-04-05 09:44
Thanks  a lot! I was under the impression, that since the call that triggered this generation to `AnalysisService/identifiers/projection` would take care of the subsequent download as well.

I'll adapt my code as soon as the change is online

**Comment by EliotRagueneau** [comment] 2024-04-08 14:33
Hi @jgriss , I think the download option should be working with the importableOnly filter now. 
As a matter of fact, I believe this is the only endpoint that is really important in your case regarding this issue, you can probably leave the others without it (though it doesn't hurt to include them everywhere)

In any case you should be able to test now on dev server

**Comment by jgriss** [comment] 2024-04-11 10:51
Hi @EliotRagueneau 

Thanks a lot! I just completed all tests and the issue seems to be solved! Thanks a lot!

I'll deploy our changes together with the next update. As far as I can tell, the added parameters don't cause any issue in the current API

**Comment by EliotRagueneau** [comment] 2024-10-03 11:05
Hi Johaness, finally the fix has been released with this new version 90!
Hopefully we shouldn't see this bug happening anymore :D

**Closed** 2024-10-03 13:45 UTC
Labels: bug
